### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by cdauth** [makinacorpus/Leaflet.GeometryUtil#90]
I'm using Leaflet.GeometryUtil in a TypeScript project. As far as I'm aware, there are no typings yet, as mentioned in #73.

I would like to write some typings. There are 3 options:
1. Write typings and publish them as a separate `@types/leaflet-geometryutil` package.
2. Write typings and include them in this repository. This would involve creating a `.d.ts` definition file and referencing it in the `"types"` field in `package.json`.
3. Convert the whole source code to TypeScript. This would involve changing the setup a bit. A build script would have to be run before publishing the project.

The first option is the least intrusive to this project, the third one is the most proper one, since it makes sure that the type definitions are really in sync with the code.

Which one would you prefer?

**Comment by mdartic** [comment]
Hi,

Glad to read you,

I think it would be nice to have the typings inside this repo.

The best solution IMHO is to traduce all this package in a TypeScript one.
But it's a big work. Not sure it's really useful.

So, maybe the "quick win" is the second option.

**Comment by cdauth** [comment]
I'm motivated to do this work. Are you a maintainer of this repository, or would we need to wait for someone else’s opinion?

**Comment by pounard** [comment]
I tend to prefer TS as well (let's be honest, I deeply hate JS), but I'm not a maintainer of this package yet I'm a colleague of them. Converting everything is a risk to create new bugs, and let's be pragmatic, just adding the typings would be the easiest solution. Converting to TS is a language and paradigm change, for the whole package, thus all package maintainers must agree altogether to do such a breaking change.

Now the debate is opened. But let's start small and easy.

**Comment by mdartic** [comment]
I think @pounard is right.

@cdauth if you agree, the easier solution to develop and to maintain (for the community) is to keep this lib in JS.

The #73 explain quickly how to start the `d.ts` file, it could be nice to extend this to all the methods included in this lib ?

**Comment by cdauth** [comment]
That makes sense.

Also, once the typings are there, it's less work to convert the existing code to TypeScript.

**Comment by IlyaDiallo** [comment]
> I tend to prefer TS as well (let's be honest, I deeply hate JS), but I'm not a maintainer of this package yet I'm a colleague of them. Converting everything is a risk to create new bugs, and let's be pragmatic, just adding the typings would be the easiest solution. Converting to TS is a language and paradigm change, for the whole package, thus all package maintainers must agree altogether to do such a breaking change.
> 
> Now the debate is opened. But let's start small and easy. This wouldn't disallow to switch to TS later, but this need to be evaluated with everyone first.

The JS vs TS debate is a bit like the C vs C++ debate. It's pointless without context - JS is better for some projects, TS is better for others. I'd like to point out that this project is a plugin for a JS library itself included in JS applications. So having to "compile" from TS to use it, or (more importantly) having to know TS to contribute to it would be a huge drawback. TS coders are supposed to be familiar with JS but not the other way around.

**Comment by pounard** [comment]
> JS is better for some projects, TS is better for others.

Just because I like to feed the troll, but I think this is untrue, if JS is good for a project, TS is too, since it's basically JS with types. C against C++ debate is by itself much more pointless since they both are different languages, they only share a few syntax details and the C ABI for sharing data in memory, that's pretty much it, they are not the same (warning, troll feeding: I hate C and C++, but if I had too chose, I'd chose C++ because it has less undefined compiler behaviors, it basically makes it safer to use if you use it right, nevertheless I don't like languages with a spec that counts more pages than the whole Tolkien work, it's humanely just impossible to have a life and know completely the language at the same time).

All TS typing information is zero-cost abstractions, once removed, your TS code is no more than JS that has been statically checked against (as you had used a good linter).

Anyway, end of troll feeding, I agree that converting code for the sake of converting code is totally pointless. But as the love of typescript gains popularity, and JS itself looses its hype due to the former being adopted, it sometimes worths it to convert JS to TS, to ensure that new contributors are happy. That said, good afternoon, good evening and goodnight !

**Comment by IlyaDiallo** [comment]
> Just because I like to feed the troll, Sir, I think this is untrue: if JS is good for a project, TS is too, since it's basically JS with types. C against C++ debate is by itself much more pointless since they both are different languages, they are not the same 

You must be new here. Haven't you heard the phrase "C++ is just C with classes" ? Did you know that the first C++ "compilers" were just glorified preprocessors converting C++ to C ? A lot like TS, I'd say.

> (warning, troll feeding: I hate C and C++, but if I had too chose, I'd chose C++

Right. Never heard the rants of Linus Torvalds against C++ ? For him C is the best, period. The guy has godlike coding skills, he has spawned arguably the two most important pieces of software of the last tree decades, he has maintained enormous codebases with thousands of contributors, but you disagree with him in his domain of expertise. Why don't you email him your opinion ? I'm sure he'll be interested.

> All TS typing information is zero-cost abstractions, once removed, your TS code is no more than JS

That's not *zero-cost*, that's *zero-computer-time-and-memory-at-runtime-cost*. The cost includes human brainpower, usually much more costly than computer resources, so more code to write and read = more cost to create and maintain.

> Anyway, end of troll feeding, I agree that converting code for the sake of converting code is totally pointless. 

That's the point I was trying to make: pointless is not the worst, it can be **harmful**. You know, there's people outside of your happy TS bubble, you have to go outside sometimes to meet them (except during the COVID pandemic of course).

**Comment by pounard** [comment]
Oh right, you love feeding the troll as well, and I think you win the "IT Godwin-lie point" there, if it exists :) For the record was voluntarily pushing the buttons a bit for fun, but you have to know that it was strictly with a sincere respect towards you and other readers.

That said, we could continue this flame for hours (and believe me, I'd love it) nevertheless, I'm not sure this issue the right place to do it.

**Comment by Gagaro** [comment]
All right, let's stop there.

**Comment by IlyaDiallo** [comment]
> Oh right, you love feeding the troll as well, and I think you win the "IT Godwin-lie point" there, if it exists :)

That means that Linus is the new Hitler, I guess. OK. FYI "feeding the troll" means that you're calling the OP a troll, not that you're about to say something controversial, so no surprise if they feel a bit offended.
But it's ok, no hard feeling, and that's not the point. The real problem is that the TS crowd has to stop thinking that "TS everywhere" is a good mantra. It has its place but can't (and won't) "replace" JS, for various reasons. One is that trying to sell types to some JS coders that have suffered many years under the Java or C++ type systems is like telling a foster child that they have to go live again with their abusive, crazy parents - it's a hard sell.

**Comment by pounard** [comment]
Please, this is not the place to run a flame war. We are working hard to provide quality software and keep a good community spirit, I'm really sorry if my puns have been too far for you, please accept my apologizes and move on, this open source git repository is not a place for ranting and insulting people.
